import type { ServiceCategory, Product, Solution, QuestionnaireStep } from './types'

export const COMPLIANCE_DOMAINS = [
  'Consent & Notice',
  'Data Principal Rights',
  'Data Minimisation & Retention',
  'Data Security & Breach',
  'Vendors & Third Parties',
  'Governance & Readiness',
] as const

export const NAV_LINKS = [
  { label: 'Services', href: '/services' },
  { label: 'Products', href: '/products' },
  { label: 'Solutions', href: '/solutions' },
  { label: 'About', href: '/about' },
  { label: 'Contact', href: '/contact' },
  { label: 'Partnership', href: '/partnership' },
] as const

export const STATS = [
  { value: '50+', label: 'Consulting Engagements' },
  { value: '100+', label: 'Enterprise Users' },
  { value: '6', label: 'Compliance Frameworks' },
  { value: '18', label: 'Compliance Checkpoints' },
  { value: '₹250 Cr', label: 'Max Penalty per Violation' },
  { value: '40+', label: 'Sub-Offerings Across 8 Categories' },
] as const

export const SERVICE_CATEGORIES: ServiceCategory[] = [
  {
    id: 'advisory-legal-regulatory',
    title: 'Advisory, Legal and Regulatory',
    icon: 'Scale',
    description: 'Strategic advisory services grounded in the Digital Personal Data Protection Act 2023 and the November 2025 Rules, covering applicability assessments, policy design, rights advisory, Significant Data Fiduciary readiness, and cross-border transfer governance.',
    subOfferings: [
      {
        title: 'DPDP Readiness and Regulatory Advisory',
        description: 'Comprehensive applicability assessment against DPDP 2023 Sections 5-16 and the November 2025 Rules. Identifies your obligations as a Data Fiduciary or Significant Data Fiduciary under Section 10, mapping penalty exposure across all six compliance domains. Delivers a prioritised roadmap covering Consent & Notice, Data Principal Rights, Data Minimisation, Data Security, Vendors, and Governance.',
        dpdpSections: ['5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16'],
        penalties: ['₹50 Crore', '₹200 Crore', '₹250 Crore'],
        whoIsThisFor: 'Data Fiduciaries beginning DPDP compliance or seeking clarity on regulatory obligations',
      },
      {
        title: 'Privacy Governance, Policy and Consent Design',
        description: 'Design DPDP-compliant privacy policies meeting Section 5 notice requirements and consent frameworks requiring free, specific, informed, and unambiguous consent under Section 6(1). Establishes granular consent per data type and purpose as mandated by Section 6(2), ensuring withdrawal is as easy as giving consent per Section 6(4).',
        dpdpSections: ['5', '6(1)', '6(2)', '6(4)'],
        penalties: ['₹50 Crore', '₹200 Crore'],
        whoIsThisFor: 'Organisations needing compliant privacy policies and consent architectures',
      },
      {
        title: 'Rights, Grievance and DPO Advisory',
        description: 'Build end-to-end workflows for Data Principal rights including access, correction, and erasure under Sections 11-13. Establishes a grievance officer with published contact details and defined SLAs per Section 13(3). Designs verifiable parental consent processes for children\'s data as required by Section 9.',
        dpdpSections: ['9', '11', '12', '13', '13(3)'],
        penalties: ['₹200 Crore', '₹250 Crore'],
        whoIsThisFor: 'Organisations processing children\'s data or handling high volumes of Data Principal requests',
      },
      {
        title: 'SDF and Enhanced Compliance Readiness',
        description: 'Assessment against Significant Data Fiduciary criteria under Section 10, covering mandatory Data Protection Impact Assessments, annual audits, algorithmic accountability requirements, and mandatory DPO appointment. Prepares organisations for the heightened obligations and scrutiny that SDF classification triggers.',
        dpdpSections: ['10', '10(2)', '10(2)(b)'],
        penalties: ['₹250 Crore'],
        whoIsThisFor: 'Large enterprises and organisations likely to be classified as Significant Data Fiduciaries',
      },
      {
        title: 'Data Sovereignty and Executive Advisory',
        description: 'Cross-border transfer governance aligned with Section 16, assessing permissibility of data flows to cloud servers, group entities, and international destinations. Delivers transfer impact assessments and contractual safeguard frameworks to ensure lawful international data movement.',
        dpdpSections: ['16'],
        penalties: ['₹250 Crore'],
        whoIsThisFor: 'Multinational organisations transferring personal data outside India',
      },
    ],
  },
  {
    id: 'privacy-operations-data-governance',
    title: 'Privacy Operations and Data Governance',
    icon: 'Database',
    description: 'Operational privacy services covering data inventory and flow mapping, consent lifecycle management, retention and deletion governance, processor and vendor oversight, and the design of sustainable privacy operating models.',
    subOfferings: [
      {
        title: 'Data Inventory, Visibility and Flow Mapping',
        description: 'Build a live inventory of all personal data your organisation holds, where it resides, who can access it, and how it flows between systems. Maps data lineage and traceability to satisfy Section 8(5) reasonable security safeguard requirements and provides the foundational visibility needed for every other compliance activity.',
        dpdpSections: ['8(5)'],
        penalties: ['₹250 Crore'],
        whoIsThisFor: 'Organisations lacking visibility into their personal data landscape',
      },
      {
        title: 'Consent, Rights and Grievance Operations',
        description: 'End-to-end consent lifecycle management covering collection, versioning, withdrawal, and preference synchronisation across all touchpoints. Automated DSAR workflows with defined response timelines (recommended 30 days) for access, correction, and erasure requests under Sections 11-13.',
        dpdpSections: ['6(1)', '6(2)', '6(4)', '11', '12', '13', '13(3)'],
        penalties: ['₹50 Crore', '₹200 Crore'],
        whoIsThisFor: 'Organisations managing high-volume consent and Data Principal requests across multiple channels',
      },
      {
        title: 'Retention, Deletion and Records Governance',
        description: 'Retention schedules mapped to DPDP Section 8(7) requiring data erasure once the purpose is fulfilled or consent is withdrawn. Automated deletion and anonymisation pipelines with quarterly testing cycles to verify complete data removal across all storage systems.',
        dpdpSections: ['8(7)'],
        penalties: ['₹250 Crore'],
        whoIsThisFor: 'Organisations with complex data lifecycles or legacy systems holding stale personal data',
      },
      {
        title: 'Processor, Vendor and Data-Sharing Governance',
        description: 'Vendor contract audits against Section 8(2) covering Data Processing Agreement clauses, right-to-audit provisions, sub-processor restrictions, and breach notification pass-through requirements. Establishes a processor register covering all systems and third parties receiving personal data.',
        dpdpSections: ['8(2)'],
        penalties: ['₹250 Crore'],
        whoIsThisFor: 'Organisations relying on multiple processors, cloud vendors, or data-sharing arrangements',
      },
      {
        title: 'Privacy Operating Model and Operational Support',
        description: 'Design and implement sustainable privacy operating models with designated compliance leads, function-specific accountability matrices, and board reporting channels. For Significant Data Fiduciaries, ensures compliance with Section 10(2)(b) mandatory DPO requirements.',
        dpdpSections: ['8(1)', '10(2)(b)'],
        penalties: ['₹250 Crore'],
        whoIsThisFor: 'Organisations seeking a sustainable, scalable privacy governance structure',
      },
    ],
  },
  {
    id: 'data-sovereignty-cross-border',
    title: 'Data Sovereignty and Cross-Border Governance',
    icon: 'Globe',
    description: 'Specialised services for data residency, cross-border transfer governance, jurisdictional risk assessment, sovereign architecture advisory, and evidence-based sovereignty assurance aligned with DPDP Section 16.',
    subOfferings: [
      {
        title: 'Data Residency and Localisation Advisory',
        description: 'Assessment of all data flows crossing Indian borders under Section 16 of DPDP 2023. Reviews cloud provider data residency configurations and performs permissibility assessments for each destination country, factoring in government-notified restricted jurisdictions.',
        dpdpSections: ['16'],
        penalties: ['₹250 Crore'],
        whoIsThisFor: 'Organisations using international cloud providers or processing data offshore',
      },
      {
        title: 'Cross-Border Transfer and Data-Sharing Governance',
        description: 'Contractual safeguard frameworks for lawful cross-border data transfers including transfer impact assessments, standard contractual clauses, and data-sharing control designs. Ensures every international data movement has documented legal basis and appropriate protections.',
        dpdpSections: ['16'],
        penalties: ['₹250 Crore'],
        whoIsThisFor: 'Multinational enterprises with data flows to group entities or international partners',
      },
      {
        title: 'Jurisdictional and Access Risk Review',
        description: 'Foreign access-risk review assessing whether personal data stored outside India could be subject to access by foreign governments or courts. Sub-processor geography and access assessment with jurisdictional exposure mapping for each data processing location.',
        dpdpSections: ['16'],
        penalties: ['₹250 Crore'],
        whoIsThisFor: 'Organisations concerned about foreign government data access or geopolitical risk',
      },
      {
        title: 'Sovereign Architecture and Hosting Advisory',
        description: 'Sovereign cloud advisory covering deployment pattern review for data localisation compliance. Architecture alignment with DPDP transfer provisions including hybrid cloud designs, edge computing strategies, and data partitioning approaches that satisfy residency requirements.',
        dpdpSections: ['16'],
        penalties: ['₹250 Crore'],
        whoIsThisFor: 'Organisations redesigning infrastructure to meet data localisation requirements',
      },
      {
        title: 'Sovereignty Assurance and Evidence Support',
        description: 'Evidence collection and documentation for sovereignty compliance, including audit-ready reporting for cross-border governance. Produces regulator-ready evidence packs demonstrating lawful data transfer practices and residency compliance.',
        dpdpSections: ['16'],
        penalties: ['₹250 Crore'],
        whoIsThisFor: 'Organisations preparing for regulatory audits or due diligence on cross-border data practices',
      },
    ],
  },
  {
    id: 'ai-governance-responsible-ai',
    title: 'AI Governance and Responsible AI',
    icon: 'Brain',
    description: 'AI governance services covering strategy and operating model design, AI policy and risk frameworks, responsible AI controls, Generative AI governance, and AI Governance Office establishment aligned with DPDP algorithmic accountability requirements.',
    subOfferings: [
      {
        title: 'AI Governance Strategy and Operating Model',
        description: 'AI governance framework aligned with DPDP algorithmic accountability requirements for Significant Data Fiduciaries under Section 10. Establishes the organisational structure, decision rights, and processes needed to govern AI systems responsibly while maintaining compliance.',
        dpdpSections: ['10'],
        penalties: ['₹250 Crore'],
        whoIsThisFor: 'Organisations deploying AI systems that process personal data at scale',
      },
      {
        title: 'AI Policy, Use-Case and Risk Governance',
        description: 'Comprehensive AI use-case inventory, risk-tiering, and classification framework. Develops AI policy frameworks including acceptable-use policies, approval and exception governance processes, and risk assessment methodologies for both internal and third-party AI systems.',
        dpdpSections: ['10'],
        penalties: ['₹250 Crore'],
        whoIsThisFor: 'Organisations with multiple AI use cases requiring systematic governance',
      },
      {
        title: 'Responsible AI Controls and Human Oversight',
        description: 'Human oversight and accountability models for AI-driven decisions affecting Data Principals. Responsible AI control frameworks covering fairness, transparency, explainability, and documentation requirements aligned with emerging regulatory expectations.',
        dpdpSections: ['10'],
        penalties: ['₹250 Crore'],
        whoIsThisFor: 'Organisations using AI for automated decision-making impacting individuals',
      },
      {
        title: 'Generative AI and Third-Party AI Governance',
        description: 'GenAI governance framework covering prompt data, training data, and output data governance. Third-party AI vendor risk reviews assessing data handling practices, model transparency, and contractual safeguards for AI services processing personal data.',
        dpdpSections: ['8(2)', '10'],
        penalties: ['₹250 Crore'],
        whoIsThisFor: 'Organisations adopting GenAI tools or integrating third-party AI services',
      },
      {
        title: 'AI Governance Office and Accountability Design',
        description: 'Design and operationalise an AI Governance Office with defined mandate, reporting lines, and accountability models. Aligns governance structure with regulatory expectations including DPDP algorithmic accountability and emerging AI-specific regulations.',
        dpdpSections: ['10'],
        penalties: ['₹250 Crore'],
        whoIsThisFor: 'Organisations seeking to centralise and formalise AI governance',
      },
    ],
  },
  {
    id: 'technical-implementation',
    title: 'Technical Implementation and Continuous Compliance',
    icon: 'Code',
    description: 'Hands-on technical implementation services covering privacy workflow deployment, retention automation, evidence and traceability architecture, platform integration, and continuous compliance monitoring through automated scanning.',
    subOfferings: [
      {
        title: 'Privacy and Rights Workflow Implementation',
        description: 'Privacy-by-design implementation covering consent workflow deployment via Consent Cockpit (consent banners, preference centres, SDK integration). Rights and grievance workflow automation with configurable response timelines and multi-channel intake.',
        dpdpSections: ['5', '6(1)', '6(2)', '6(4)', '11', '12', '13'],
        penalties: ['₹50 Crore', '₹200 Crore'],
        whoIsThisFor: 'Organisations ready to implement technical privacy controls and automated workflows',
      },
      {
        title: 'Retention, Deletion and Control Automation',
        description: 'Automated retention and deletion pipelines mapped to DPDP Section 8(7), ensuring data is erased once the processing purpose is fulfilled or consent is withdrawn. Evidence and audit-trail architecture with purpose-limitation enforcement across all data stores.',
        dpdpSections: ['8(7)'],
        penalties: ['₹250 Crore'],
        whoIsThisFor: 'Organisations needing automated data lifecycle management across complex environments',
      },
      {
        title: 'Evidence, Traceability and Compliance Reporting',
        description: 'Immutable consent audit trails using append-only consent logs per DPDP proof-of-consent requirements. Privacy telemetry dashboards providing real-time visibility into compliance posture. Compliance health scoring on a 0-100 scale with A-F grading.',
        dpdpSections: ['6(1)', '6(2)', '8(5)'],
        penalties: ['₹250 Crore'],
        whoIsThisFor: 'Organisations needing regulator-ready evidence and continuous compliance visibility',
      },
      {
        title: 'Platform Integration and Control Orchestration',
        description: 'Control orchestration across application, infrastructure, and data layers with integration into the Consent Cockpit ecosystem: consent management, DSAR workflows, code scanning, and infrastructure scanning. Unified compliance view across all organisational systems.',
        dpdpSections: ['8(2)', '8(5)', '10'],
        penalties: ['₹250 Crore'],
        whoIsThisFor: 'Organisations seeking unified compliance control across diverse technology stacks',
      },
      {
        title: 'Continuous Compliance and AI Workflow Enablement',
        description: 'Continuous compliance monitoring via automated Playwright-powered headless browser scanning for cookies, trackers, policies, and DSAR mechanisms. AI workflow governance controls and SDLC/DevSecOps integration ensuring privacy is embedded in development pipelines.',
        dpdpSections: ['5', '6', '8(5)', '10'],
        penalties: ['₹250 Crore'],
        whoIsThisFor: 'Organisations seeking always-on compliance monitoring and DevSecOps privacy integration',
      },
    ],
  },
  {
    id: 'assurance-audit-risk',
    title: 'Assurance, Audit and Risk Validation',
    icon: 'ShieldCheck',
    description: 'Independent assurance services covering readiness and maturity assessments, gap analysis with penalty exposure calculations, control effectiveness reviews, DPIA support, and audit evidence validation across all six DPDP compliance domains.',
    subOfferings: [
      {
        title: 'Readiness and Maturity Assessments',
        description: 'DPDP readiness assessment across six compliance domains and 18 compliance checkpoints. Privacy maturity assessment benchmarking your current state against regulatory expectations. AI governance maturity assessment for organisations deploying algorithmic decision-making.',
        dpdpSections: ['5', '6', '8', '9', '10', '11', '12', '13', '16'],
        penalties: ['₹50 Crore', '₹200 Crore', '₹250 Crore'],
        whoIsThisFor: 'Organisations seeking an independent baseline assessment of their compliance posture',
      },
      {
        title: 'Gap Assessment and Remediation Planning',
        description: 'Detailed gap analysis with penalty exposure calculation per compliance domain, up to ₹250 Crore per violation across Consent & Notice, Data Principal Rights, Data Minimisation, Data Security, Vendors, and Governance. Delivers prioritised remediation roadmaps with implementation timelines.',
        dpdpSections: ['5', '6', '8', '9', '10', '11', '12', '13', '16'],
        penalties: ['₹50 Crore', '₹200 Crore', '₹250 Crore'],
        whoIsThisFor: 'Organisations with identified gaps needing structured remediation plans',
      },
      {
        title: 'Control Design and Effectiveness Reviews',
        description: 'Design effectiveness and operating effectiveness reviews of privacy controls. Control testing against DPDP Section 8 obligations covering security safeguards, breach notification preparedness, and data processing agreements with vendors.',
        dpdpSections: ['8', '8(2)', '8(5)', '8(6)'],
        penalties: ['₹250 Crore'],
        whoIsThisFor: 'Organisations with existing controls needing independent validation',
      },
      {
        title: 'SDF, DPIA and Algorithmic Due Diligence Support',
        description: 'Data Protection Impact Assessment methodology and execution, mandatory for Significant Data Fiduciaries under Section 10. Algorithmic due diligence covering AI systems processing personal data. SDF criteria self-assessment with evidence-based classification guidance.',
        dpdpSections: ['10', '10(2)'],
        penalties: ['₹250 Crore'],
        whoIsThisFor: 'Organisations required to conduct DPIAs or undergoing SDF classification',
      },
      {
        title: 'Audit Evidence and Assurance Reporting',
        description: 'Evidence-pack validation ensuring all compliance documentation meets regulatory standards. Internal audit support, board and regulator assurance reporting, and continuous control-testing design for ongoing compliance verification.',
        dpdpSections: ['10', '10(2)'],
        penalties: ['₹250 Crore'],
        whoIsThisFor: 'Organisations preparing for regulatory inspections or board-level compliance reporting',
      },
    ],
  },
  {
    id: 'cyber-privacy-incident-resilience',
    title: 'Cyber Privacy and Incident Resilience',
    icon: 'Shield',
    description: 'Security-meets-privacy services covering safeguard assessments, proactive risk validation, breach readiness planning, regulatory incident alignment, and resilience exercises to ensure DPDP Section 8(5)-8(6) compliance.',
    subOfferings: [
      {
        title: 'Privacy Safeguard and Exposure Assessments',
        description: 'Security safeguard review against Section 8(5) requirements covering documented encryption standards, access control matrices, and audit log configurations. Gap assessment against ISO 27001 and NIST CSF frameworks to identify privacy-specific security deficiencies.',
        dpdpSections: ['8(5)'],
        penalties: ['₹250 Crore'],
        whoIsThisFor: 'Organisations needing validation of technical security safeguards for personal data',
      },
      {
        title: 'Proactive Privacy Risk Validation',
        description: 'Offensive privacy assessment and attack-surface review targeting personal data exposure points. Privacy exposure assessment of publicly accessible website surfaces including cookie and tracker behaviour, consent mechanisms, and policy compliance.',
        dpdpSections: ['8(5)', '8(6)'],
        penalties: ['₹250 Crore'],
        whoIsThisFor: 'Organisations seeking proactive identification of privacy vulnerabilities before regulators do',
      },
      {
        title: 'Breach Readiness and Incident Response Planning',
        description: 'Incident response runbooks for DPDP Section 8(6) breach notification requirements. Data Protection Board notification templates, 72-hour response readiness protocols, and alignment with CERT-In and DPDP reporting obligations.',
        dpdpSections: ['8(6)'],
        penalties: ['₹250 Crore'],
        whoIsThisFor: 'Organisations lacking documented breach response procedures or needing regulatory alignment',
      },
      {
        title: 'Regulatory Incident Alignment and Third-Party Coordination',
        description: 'Third-party breach response coordination for incidents originating at processors or vendors. Regulatory incident communication frameworks including notification to the Data Protection Board and affected Data Principals as required by Section 8(6).',
        dpdpSections: ['8(6)', '8(2)'],
        penalties: ['₹250 Crore'],
        whoIsThisFor: 'Organisations with complex vendor ecosystems needing coordinated breach response',
      },
      {
        title: 'Resilience Exercises and Post-Incident Support',
        description: 'Tabletop exercises simulating breach scenarios tailored to DPDP notification timelines. Post-incident evidence collection and remediation support. Privacy-security control convergence review ensuring cyber and privacy teams operate in alignment.',
        dpdpSections: ['8(5)', '8(6)'],
        penalties: ['₹250 Crore'],
        whoIsThisFor: 'Organisations seeking to test and improve their incident response capabilities',
      },
    ],
  },
  {
    id: 'managed-services',
    title: 'Managed Services and Capability Enablement',
    icon: 'Headphones',
    description: 'Outsourced and co-managed privacy services covering virtual DPO, managed privacy operations, managed governance, co-managed enterprise support, and training programmes for sustained DPDP compliance.',
    subOfferings: [
      {
        title: 'Privacy Office and vDPO Services',
        description: 'Privacy Office as a Service providing a named compliance owner with defined mandate and board reporting channels. Virtual DPO services mandatory for Significant Data Fiduciaries under Section 10(2)(b), delivering ongoing regulatory liaison and compliance oversight.',
        dpdpSections: ['10', '10(2)(b)'],
        penalties: ['₹250 Crore'],
        whoIsThisFor: 'Organisations requiring a DPO without the capacity to hire a full-time resource',
      },
      {
        title: 'Managed Privacy Operations',
        description: 'Managed rights and grievance operations handling Data Principal requests end-to-end. Managed consent and preference operations ensuring continuous compliance. Managed processor governance including contract reviews and vendor risk assessments.',
        dpdpSections: ['6(1)', '6(4)', '8(2)', '11', '12', '13'],
        penalties: ['₹50 Crore', '₹200 Crore', '₹250 Crore'],
        whoIsThisFor: 'Organisations needing operational privacy support without building an in-house team',
      },
      {
        title: 'Managed Governance, Reporting and Incident Support',
        description: 'Managed privacy reporting with regular compliance dashboards and board-ready summaries. Managed AI governance support for organisations deploying algorithmic systems. Managed privacy incident support providing first-responder capability for breach scenarios.',
        dpdpSections: ['8(6)', '10'],
        penalties: ['₹250 Crore'],
        whoIsThisFor: 'Organisations seeking ongoing governance oversight and incident response readiness',
      },
      {
        title: 'Co-Managed Enterprise Support',
        description: 'Co-managed support model for mature InfoSec, legal, and audit teams needing specialised DPDP expertise. Build-operate-transfer capability model that embeds compliance knowledge within your organisation while providing expert backing.',
        dpdpSections: ['8', '10'],
        penalties: ['₹250 Crore'],
        whoIsThisFor: 'Mature organisations with existing teams needing specialist DPDP augmentation',
      },
      {
        title: 'Training, Capability Build and Transition Support',
        description: 'Function-specific DPDP training delivered to Legal, IT, HR, and Operations teams as required by Section 8(1). Role-based modules covering consent handling, breach response, rights management, and vendor governance. Annual refresher schedules with privacy embedded in product and project lifecycles.',
        dpdpSections: ['8(1)'],
        penalties: ['₹250 Crore'],
        whoIsThisFor: 'Organisations building internal DPDP competency across all business functions',
      },
    ],
  },
]

export const PRODUCTS: Product[] = [
  {
    id: 'consent-platform',
    name: 'Consent Cockpit Platform',
    tagline: 'Consent that satisfies Section 6 from capture to withdrawal to proof',
    description: 'Enterprise-grade consent management platform built specifically for DPDP 2023 compliance. Handles the full consent lifecycle from banner presentation through granular preference management to immutable audit trails, ensuring every consent interaction is legally defensible.',
    features: [
      {
        title: 'Consent Banner Management',
        description: 'Customisable cookie consent banners with JSONB config-driven layout, content, styling, and categories. Region-aware consent modes supporting opt-in for GDPR/EU, opt-out for CCPA, and DPDP-compliant flows for India with script blocking before consent and multi-language support across DPDP Schedule languages.',
      },
      {
        title: 'Cookie Discovery and Classification',
        description: 'Playwright-powered headless browser scanning discovers all cookies including HTTP and JavaScript-set variants. Auto-classification against a 500+ known cookie database covering Google, Meta, Microsoft, HubSpot, and more with categorisation into analytics, marketing, functional, and preferences, flagging cookies set before consent as critical DPDP/GDPR violations.',
      },
      {
        title: 'Immutable Consent Audit Trail',
        description: 'Append-only consent logs that are never modified, providing the legally required proof of consent. Records visitor ID, user ID, action type, per-category choices, IP geolocation, page URL, GPC/DNT signals, regulation context, banner version, and policy version with 7-year retention for GDPR proof-of-consent compliance.',
      },
      {
        title: 'Cookie Policy Lifecycle',
        description: 'Config-driven policy editor with versioned publishing and immutable version snapshots linked to consent logs showing exactly what policy was in effect when each user consented. Auto-populated cookie tables from discovered cookies with hosted public policy pages.',
      },
      {
        title: 'Purpose-Based Consent Engine',
        description: 'Purpose registry with granular consent management supporting purpose policy versions with processor mappings. Consent resolve and decide flows enable preference centres giving Data Principals full control over their consent choices per processing purpose.',
      },
      {
        title: 'SDK and Integration',
        description: 'Single script-tag embed with organisation-signed JWT authentication using RSA/EC. Programmatic API supporting identify, getConsent, acceptAll, rejectAll, showPreferences, and withdraw operations. Safari ITP mitigation via server-set cookies and script blocking by data-cookie-category attribute.',
      },
    ],
    dpdpSections: ['5', '6(1)', '6(2)', '6(4)', '8(5)', '8(7)'],
    complianceDomains: ['Consent & Notice'],
  },
  {
    id: 'compliance-scanner',
    name: 'TrustScope Compliance Scanner',
    tagline: 'See your privacy posture the way a regulator would',
    description: 'Automated website privacy compliance scanner built on Playwright and headless Chromium. Performs a non-invasive, five-phase scan of publicly accessible website surfaces to generate a compliance health score, identify regulatory gaps, and produce actionable remediation guidance.',
    features: [
      {
        title: '5-Phase Automated Scan',
        description: 'Sequential scanning pipeline: (1) cookie and tracker discovery without consent, (2) legal page discovery via link text and URL pattern matching, (3) policy content analysis for regulatory compliance signals, (4) DSAR mechanism discovery, and (5) subpage scanning covering login, signup, checkout, and contact flows.',
      },
      {
        title: 'Compliance Health Score',
        description: '0-100 metric with A-F grading across seven weighted categories: Cookie Consent (25%), Cookie Management (15%), Privacy Policy (20%), Cookie Policy (10%), Terms of Service (5%), DSAR (15%), and Third-Party Trackers (10%). Eighteen individual pass/fail checks with point values provide granular compliance visibility.',
      },
      {
        title: 'Policy Content Analysis',
        description: 'Detects mentions of GDPR, DPDP, CCPA, data subject rights, DPO contact information, retention periods, international transfers, third-party sharing, children\'s data provisions, and cookie disclosures. Evaluates completeness against Section 5 notice requirements.',
      },
      {
        title: 'DSAR Mechanism Discovery',
        description: 'Identifies DSAR forms, privacy-related email addresses (privacy@, dpo@, dsar@), and links to third-party tools such as OneTrust, TrustArc, Enzuzo, and Termly. Verifies accessibility and functionality of rights exercise mechanisms required under Sections 11-13.',
      },
      {
        title: 'Tracker Intelligence',
        description: 'Identifies all third-party trackers firing without prior consent including Google Analytics, Meta Pixel, and advertising scripts. Cross-references detected trackers against privacy and cookie policy disclosures to flag undisclosed tracking as a Section 6 consent violation.',
      },
      {
        title: 'External Privacy Risk Score',
        description: 'Non-invasive scan of publicly accessible surfaces generating a downloadable PDF report sent via email with explicit consent. Designed as the entry point for the questionnaire conversion loop, providing immediate value while identifying opportunities for deeper compliance engagement.',
      },
    ],
    dpdpSections: ['5', '6', '8(5)', '11', '12', '13', '13(3)'],
    complianceDomains: ['Consent & Notice', 'Data Principal Rights', 'Governance & Readiness'],
  },
  {
    id: 'dsar-platform',
    name: 'DSAR Management Platform',
    tagline: 'Rights workflows that meet Section 11-13 timelines',
    description: 'Purpose-built platform for managing Data Subject Access Requests, grievance handling, and rights fulfilment workflows. Ensures organisations meet DPDP 2023 response timelines with complete audit trails for regulatory accountability.',
    features: [
      {
        title: 'Automated DSAR Workflows',
        description: 'Configurable workflow builder for access, correction, erasure, and portability requests with drag-and-drop workflow configuration. Defined response timelines with recommended 30-day completion targets and automated escalation for approaching deadlines.',
      },
      {
        title: 'Grievance Management',
        description: 'Named grievance officer publication with complaint tracking and SLA enforcement as required by Section 13(3). Escalation processes with defined timelines, evidence collection, and resolution documentation for regulatory accountability.',
      },
      {
        title: 'Multi-Channel Intake',
        description: 'Accepts requests via web forms, email, and API with automated routing based on request type and jurisdiction. Identity verification workflows ensure requests are processed securely while reducing manual triage effort.',
      },
      {
        title: 'Evidence and Reporting',
        description: 'Complete audit trail for every request from intake through fulfilment. Compliance reporting dashboards for regulators, response time analytics, and exportable evidence packs demonstrating systematic rights management.',
      },
    ],
    dpdpSections: ['11', '12', '13', '13(3)'],
    complianceDomains: ['Data Principal Rights'],
  },
  {
    id: 'infra-scanner',
    name: 'Infrastructure and Code Scanner',
    tagline: 'Compliance visibility from cloud to codebase',
    description: 'Unified scanning platform for cloud infrastructure and code repositories, identifying security misconfigurations and privacy compliance issues across AWS, Azure, and GCP environments with SDLC/DevSecOps integration.',
    features: [
      {
        title: 'Cloud Security Scanning',
        description: 'AWS, Azure, and GCP misconfiguration detection using Prowler-style security assessment. Maps infrastructure findings to DPDP Section 8(5) reasonable security safeguard requirements, prioritising remediation by compliance impact and data exposure risk.',
      },
      {
        title: 'Code Repository Scanning',
        description: 'Static analysis for privacy compliance issues including detection of hardcoded secrets, PII exposure in logs, consent bypass patterns, and insufficient access controls. Integrates into SDLC and DevSecOps pipelines for continuous code-level privacy assurance.',
      },
      {
        title: 'Compliance Dashboard',
        description: 'Unified view of infrastructure and code compliance posture across all cloud environments and repositories. Risk prioritisation engine with remediation guidance, trend analysis, and exportable reports for audit and governance teams.',
      },
    ],
    dpdpSections: ['8(5)', '8(6)', '10'],
    complianceDomains: ['Data Security & Breach'],
  },
  {
    id: 'ai-assistant',
    name: 'AI Compliance Assistant',
    tagline: 'Expert DPDP guidance in minutes, not days',
    description: 'AI-powered compliance advisory tool trained on DPDP 2023, the November 2025 Rules, GDPR, the IT Act, and global privacy frameworks. Provides instant contextual guidance, interactive compliance audits, and industry-specific recommendations.',
    features: [
      {
        title: 'AI-Powered Query Resolution',
        description: 'Trained on the full text of DPDP 2023, November 2025 Rules, GDPR, IT Act, and 20+ global privacy frameworks. Delivers instant, contextual compliance guidance with multi-language support covering English, Hindi, and 10+ regional languages from the DPDP Schedule.',
      },
      {
        title: 'DPDPA Compliance Audit',
        description: 'Interactive 18-question audit across six compliance domains: Consent & Notice, Data Principal Rights, Data Minimisation & Retention, Data Security & Breach, Vendors & Third Parties, and Governance & Readiness. Calculates penalty exposure per gap (₹100-250 Crore per question) with a downloadable PDF report featuring radar charts, domain breakdowns, and detailed findings.',
      },
      {
        title: 'Contextual Recommendations',
        description: 'Industry-specific guidance based on organisation type, data types handled, and compliance maturity stage. Automated documentation and audit trail generation supporting evidence-based compliance management.',
      },
    ],
    dpdpSections: ['All sections'],
    complianceDomains: ['All domains'],
  },
  {
    id: 'adaptive-engine',
    name: 'Adaptive Compliance Engine',
    tagline: 'Compliance that evolves with the law',
    description: 'Self-learning compliance platform that monitors regulatory changes across DPDP, GDPR, CCPA/CPRA, LGPD, and 15+ global frameworks. Automatically adapts organisational policies, workflows, and controls to maintain continuous compliance as laws evolve.',
    features: [
      {
        title: 'Regulatory Change Detection',
        description: 'Monitors DPDP amendments, new Rules notifications, and global regulatory changes in real time. Automatic impact assessment against your current compliance posture identifies which controls, policies, and workflows require updates.',
      },
      {
        title: 'Adaptive Policy Updates',
        description: 'Self-learning system that adapts policies and procedures to regulatory changes with minimal manual intervention. Customisable compliance workflows ensure organisational processes evolve alongside the legal landscape.',
      },
      {
        title: 'Multi-Framework Support',
        description: 'Unified compliance management across DPDP 2023, GDPR, CCPA/CPRA, LGPD, UAE PDPL, KSA PDPL, and more. Cross-framework gap analysis identifies overlapping requirements and harmonised controls to reduce duplication.',
      },
      {
        title: 'Continuous Monitoring',
        description: 'Real-time compliance scoring with automated gap detection and alerting. Risk scoring with trend analysis provides visibility into compliance trajectory, enabling proactive remediation before regulatory action.',
      },
    ],
    dpdpSections: ['All sections'],
    complianceDomains: ['All domains'],
  },
]

export const SOLUTIONS: Solution[] = [
  {
    id: 'ecommerce-marketplace',
    title: 'E-Commerce & Marketplace Compliance',
    industry: 'E-Commerce / Marketplace',
    description: 'Comprehensive DPDP compliance for e-commerce platforms managing customer data, marketing consent, and cross-border transactions. Addresses the unique challenges of high-volume consent collection, marketplace vendor governance, and customer rights fulfilment.',
    keyOfferings: [
      'Cookie consent management for customer-facing storefronts',
      'Marketing consent and preference centre deployment',
      'DSAR workflow automation for customer data requests',
      'Cross-border transfer governance for international commerce',
      'Vendor and marketplace seller data processing agreements',
    ],
    dpdpFocus: ['6(1)', '6(2)', '6(4)', '8(2)', '11', '12', '13', '16'],
  },
  {
    id: 'healthcare',
    title: 'Healthcare Data Protection',
    industry: 'Healthcare',
    description: 'Specialised compliance for healthcare organisations processing sensitive patient data, including enhanced security safeguards, children\'s data protections, and integration with existing health data regulations.',
    keyOfferings: [
      'Patient consent management with Section 9 children\'s data protections',
      'Enhanced data security safeguards for health records (Section 8(5))',
      'Grievance and rights workflows for patient data requests',
      'Data Fiduciary obligation mapping for healthcare entities',
      'Breach readiness specific to healthcare notification requirements',
    ],
    dpdpFocus: ['6(1)', '8(5)', '8(6)', '9', '11', '12', '13'],
  },
  {
    id: 'financial-services',
    title: 'Financial Services & FinTech',
    industry: 'Financial Services / FinTech',
    description: 'DPDP compliance tailored for financial institutions managing KYC data, transaction records, and regulatory reporting. Addresses Significant Data Fiduciary readiness and the intersection of DPDP with existing financial sector regulations.',
    keyOfferings: [
      'KYC data governance and purpose limitation controls',
      'Significant Data Fiduciary readiness assessment',
      'Regulatory reporting alignment with financial sector obligations',
      'Cross-border data transfer governance for global operations',
      'Privacy-enhanced fraud detection and monitoring compliance',
    ],
    dpdpFocus: ['6(1)', '8(5)', '10', '10(2)', '16'],
  },
  {
    id: 'saas-platform',
    title: 'SaaS & Platform Compliance',
    industry: 'SaaS / Platform',
    description: 'Multi-tenant compliance solutions for SaaS platforms acting as both Data Fiduciaries and Data Processors. Addresses API-first consent management, processor governance, and platform-level privacy architecture.',
    keyOfferings: [
      'Multi-tenant consent management via SDK integration',
      'Processor governance for platform data processing (Section 8(2))',
      'API-first privacy compliance architecture',
      'Tenant-level data isolation and retention controls',
      'Platform privacy-by-design implementation',
    ],
    dpdpFocus: ['6(1)', '6(2)', '8(2)', '8(5)', '8(7)'],
  },
  {
    id: 'regulated-enterprise',
    title: 'Regulated Enterprise Programme',
    industry: 'Regulated Enterprise',
    description: 'Full-spectrum compliance programme for organisations classified or likely to be classified as Significant Data Fiduciaries under Section 10, covering mandatory DPO appointment, annual audits, DPIAs, and algorithmic accountability.',
    keyOfferings: [
      'Significant Data Fiduciary classification assessment',
      'Mandatory DPO appointment and governance structure',
      'Annual audit programme design and execution',
      'DPIA methodology and execution framework',
      'Algorithmic accountability and AI governance controls',
    ],
    dpdpFocus: ['10', '10(2)', '10(2)(b)'],
  },
  {
    id: 'gcc-captive',
    title: 'GCC & Captive Centre Governance',
    industry: 'GCC / Captive Centre',
    description: 'Data sovereignty and cross-border governance for Global Capability Centres and captive operations processing Indian personal data. Addresses the unique challenges of offshore processing, data localisation, and jurisdictional risk.',
    keyOfferings: [
      'Data sovereignty and localisation assessment',
      'Cross-border transfer governance for group entities (Section 16)',
      'Jurisdictional access risk review',
      'Sovereign architecture and hosting advisory',
      'Transfer impact assessments and contractual safeguards',
    ],
    dpdpFocus: ['8(5)', '16'],
  },
  {
    id: 'consulting-advisory',
    title: 'Consulting & Advisory Firm Enablement',
    industry: 'Consulting / Advisory Firm',
    description: 'White-label compliance tooling and managed services for consulting firms delivering DPDP compliance to their clients. Build-operate-transfer model with training and capability development.',
    keyOfferings: [
      'White-label compliance scanner and assessment tools',
      'Managed services for client privacy operations delivery',
      'DPDP training and certification programmes for consultants',
      'Co-managed delivery model with platform access',
      'Client-facing compliance reporting and dashboards',
    ],
    dpdpFocus: ['5', '6', '8', '10', '11', '12', '13', '16'],
  },
]

export const QUESTIONNAIRE_STEPS: QuestionnaireStep[] = [
  {
    id: 'role',
    title: 'What is your role?',
    description: 'Help us tailor our recommendations to your perspective and responsibilities.',
    type: 'single',
    options: [
      { id: 'legal-compliance', label: 'Legal / Compliance / DPO', description: 'Legal counsel, compliance officer, or data protection officer', icon: 'Scale' },
      { id: 'cio-cto', label: 'CIO / CTO / Engineering', description: 'Technology leadership or engineering management', icon: 'Code' },
      { id: 'ciso-infosec', label: 'CISO / InfoSec', description: 'Information security leadership', icon: 'Shield' },
      { id: 'ceo-founder', label: 'CEO / Founder / Business Owner', description: 'Executive leadership or business ownership', icon: 'Building' },
      { id: 'audit-risk', label: 'Audit / Risk / Governance', description: 'Internal audit, risk management, or governance', icon: 'ShieldCheck' },
      { id: 'consultant', label: 'Consultant / Advisor', description: 'External consultant advising on compliance', icon: 'Users' },
    ],
  },
  {
    id: 'org-type',
    title: 'What type of organisation are you?',
    description: 'Your organisation type determines the scope and complexity of DPDP obligations.',
    type: 'single',
    options: [
      { id: 'startup-small', label: 'Startup / Small Business', description: 'Early-stage or small-scale operations', icon: 'Rocket' },
      { id: 'mid-market', label: 'Mid-Market Enterprise', description: '100-1000 employees with structured operations', icon: 'Building' },
      { id: 'large-enterprise', label: 'Large Enterprise', description: '1000+ employees, likely Significant Data Fiduciary', icon: 'Building2' },
      { id: 'platform-marketplace', label: 'Platform / Marketplace', description: 'Digital platform processing user and seller data', icon: 'Globe' },
      { id: 'gcc-global', label: 'GCC / Global Operations', description: 'Global Capability Centre or multinational operations', icon: 'Globe2' },
      { id: 'regulated', label: 'Regulated Industry', description: 'Banking, healthcare, telecom, or government', icon: 'ShieldCheck' },
    ],
  },
  {
    id: 'journey-stage',
    title: 'Where are you on your DPDP journey?',
    description: 'Understanding your current stage helps us recommend the right starting point.',
    type: 'single',
    options: [
      { id: 'just-starting', label: 'Just starting, need clarity', description: 'Haven\'t begun DPDP compliance activities', icon: 'HelpCircle' },
      { id: 'basic-policies', label: 'Have basic policies in place', description: 'Privacy policy exists but not DPDP-aligned', icon: 'FileText' },
      { id: 'know-gaps', label: 'Know our gaps, need help fixing', description: 'Completed assessment, need implementation help', icon: 'Wrench' },
      { id: 'implemented', label: 'Implemented controls, need validation', description: 'Controls in place, need assurance and audit', icon: 'CheckCircle' },
      { id: 'ongoing-support', label: 'Need ongoing operational support', description: 'Looking for managed services or DPO support', icon: 'Headphones' },
    ],
  },
  {
    id: 'data-types',
    title: 'What types of personal data do you handle?',
    description: 'Different data types trigger different DPDP obligations and penalty thresholds.',
    type: 'multi',
    options: [
      { id: 'customer-contact', label: 'Customer contact data', description: 'Names, emails, phone numbers, addresses', icon: 'User' },
      { id: 'financial-kyc', label: 'Financial / KYC data', description: 'Bank details, PAN, Aadhaar, income data', icon: 'CreditCard' },
      { id: 'health', label: 'Health / medical data', description: 'Patient records, health assessments, prescriptions', icon: 'Heart' },
      { id: 'children', label: 'Children\'s data', description: 'Data of individuals under 18 years', icon: 'Baby' },
      { id: 'employee-hr', label: 'Employee / HR data', description: 'Payroll, performance, background checks', icon: 'Users' },
      { id: 'behavioural', label: 'Behavioural / profiling data', description: 'Browsing behaviour, preferences, tracking', icon: 'BarChart' },
      { id: 'ai-training', label: 'AI prompt / training / output data', description: 'Data used in or generated by AI systems', icon: 'Brain' },
      { id: 'biometric', label: 'Biometric data', description: 'Fingerprints, facial recognition, voice prints', icon: 'Fingerprint' },
    ],
  },
  {
    id: 'priorities',
    title: 'What are your top compliance priorities?',
    description: 'Select up to 3 priorities that matter most to your organisation right now.',
    type: 'multi-limited',
    maxSelections: 3,
    options: [
      { id: 'understand-applicability', label: 'Understand DPDP applicability', description: 'Clarity on which obligations apply to us' },
      { id: 'fix-consent', label: 'Fix privacy policies and consent flows', description: 'Compliant notices, banners, and consent mechanisms' },
      { id: 'setup-rights', label: 'Set up rights and grievance workflows', description: 'DSAR fulfilment and grievance officer processes' },
      { id: 'vendor-risk', label: 'Manage vendor privacy risk', description: 'Processor agreements and vendor governance' },
      { id: 'data-sovereignty', label: 'Address data sovereignty concerns', description: 'Cross-border transfer and data residency' },
      { id: 'ai-governance', label: 'Govern AI and GenAI usage', description: 'AI governance, accountability, and transparency' },
      { id: 'audit-prep', label: 'Prepare for audit and assurance', description: 'Readiness assessment and evidence preparation' },
      { id: 'breach-readiness', label: 'Improve breach readiness', description: 'Incident response and notification preparedness' },
      { id: 'workflow-automation', label: 'Implement workflow automation', description: 'Technical implementation of privacy controls' },
      { id: 'dpo-support', label: 'Get DPO or vDPO support', description: 'Outsourced data protection officer services' },
    ],
  },
  {
    id: 'support-type',
    title: 'What type of support are you looking for?',
    description: 'This helps us recommend the right mix of products and services.',
    type: 'multi',
    options: [
      { id: 'quick-assessment', label: 'Quick readiness assessment', description: 'Fast baseline check of compliance posture', icon: 'Zap' },
      { id: 'legal-advisory', label: 'Legal and regulatory advisory', description: 'Expert guidance on DPDP obligations', icon: 'Scale' },
      { id: 'technical-implementation', label: 'Technical implementation', description: 'Hands-on deployment of compliance tools', icon: 'Code' },
      { id: 'audit-support', label: 'Audit and assurance support', description: 'Independent validation and evidence preparation', icon: 'ShieldCheck' },
      { id: 'managed-ops', label: 'Managed operations', description: 'Outsourced privacy operations and DPO', icon: 'Headphones' },
      { id: 'training', label: 'Training and capability building', description: 'Team training on DPDP obligations', icon: 'GraduationCap' },
    ],
  },
  {
    id: 'scan-option',
    title: 'Would you like a free privacy risk score?',
    description: 'We can scan your website\'s public-facing privacy posture and generate a compliance health report, the same way a regulator would assess you.',
    type: 'boolean',
    options: [
      { id: 'yes', label: 'Yes, scan my website', description: 'Get a free compliance health score with actionable insights' },
      { id: 'no', label: 'Skip for now', description: 'Go straight to personalised recommendations' },
    ],
  },
  {
    id: 'scan-details',
    title: 'Enter your website details',
    description: 'We\'ll scan your website and send the compliance report to your email.',
    type: 'form',
  },
  {
    id: 'contact-details',
    title: 'Tell us about yourself',
    description: 'So we can personalise your report and recommendations.',
    type: 'form',
  },
  {
    id: 'consent',
    title: 'Consent and submission',
    description: 'Review your selections and provide consent to proceed.',
    type: 'boolean',
    options: [
      { id: 'consent-given', label: 'I consent to Consent Cockpit processing my data for compliance assessment purposes', description: 'Your data will be processed in accordance with our privacy policy and DPDP 2023' },
    ],
  },
]
